## Numpy Exercise

In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3])

In [3]:
a2 = np.array([[1,2,3],[4,5,6]])

In [4]:
a1.ndim,a2.ndim

(1, 2)

In [5]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3.ndim

3

In [6]:
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [8]:
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((1, 3, 3), 3, dtype('int32'), 9, numpy.ndarray)

In [9]:
import pandas as pd
d_frame = pd.DataFrame(a2)
d_frame

0  1  2
0  1  2  3
1  4  5  6

In [10]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
rand_arr = np.random.randint(0,10,size=(7,2))
rand_arr

array([[2, 1],
       [3, 2],
       [4, 5],
       [0, 1],
       [1, 8],
       [6, 1],
       [1, 5]])

In [14]:
rand_arr2 = np.random.random((3,5))
rand_arr2

array([[0.65481492, 0.88380314, 0.50435574, 0.61900239, 0.40685208],
       [0.51679191, 0.76900635, 0.67124917, 0.23823842, 0.75760481],
       [0.75345866, 0.69993417, 0.7167705 , 0.95219518, 0.33061414]])

In [15]:
np.random.seed(42)
rand_arr3 = np.random.randint(0,10,size=(4,6))
rand_arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [16]:
rand_arr4 = np.random.randint(1,10,size=(3,7))
rand_arr4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [17]:
np.unique(rand_arr4)

array([1, 2, 3, 4, 5, 7, 9])

In [18]:
rand_arr4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [19]:
rand_arr4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [20]:
rand_arr4[:2,:2]

array([[9, 1],
       [5, 3]])

In [21]:
array1 = np.random.randint(1,10,size=(3,5))
array2 = np.ones((3,5))
array1

array([[7, 8, 3, 1, 4],
       [2, 8, 4, 2, 6],
       [6, 4, 6, 2, 2]])

In [22]:
array2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
array3 = array1 + array2
array3

array([[8., 9., 4., 2., 5.],
       [3., 9., 5., 3., 7.],
       [7., 5., 7., 3., 3.]])

In [24]:
array4 = np.ones((3,5))
array4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
array2+array4

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [26]:
array3-array2

array([[7., 8., 3., 1., 4.],
       [2., 8., 4., 2., 6.],
       [6., 4., 6., 2., 2.]])

In [27]:
array3 * array2

array([[8., 9., 4., 2., 5.],
       [3., 9., 5., 3., 7.],
       [7., 5., 7., 3., 3.]])

In [28]:
array3 **2

array([[64., 81., 16.,  4., 25.],
       [ 9., 81., 25.,  9., 49.],
       [49., 25., 49.,  9.,  9.]])

In [29]:
np.square(array3)

array([[64., 81., 16.,  4., 25.],
       [ 9., 81., 25.,  9., 49.],
       [49., 25., 49.,  9.,  9.]])

In [30]:
np.mean(array3)

5.333333333333333

In [31]:
np.max(array3)

9.0

In [32]:
np.min(array3)

2.0

In [33]:
np.std(array3)

2.270584848790187

In [34]:
np.var(array3)

5.155555555555556

In [35]:
np.reshape(array3,(3,5,1))
array3

array([[8., 9., 4., 2., 5.],
       [3., 9., 5., 3., 7.],
       [7., 5., 7., 3., 3.]])

In [36]:
array3.T

array([[8., 3., 7.],
       [9., 9., 5.],
       [4., 5., 7.],
       [2., 3., 3.],
       [5., 7., 3.]])

In [37]:
arr1 = np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(0,10,size=(3,2))
arr1,arr2

(array([[9, 3, 7],
        [6, 8, 7],
        [4, 1, 4]]),
 array([[7, 9],
        [8, 8],
        [0, 8]]))

In [38]:
np.dot(arr1,arr2)

array([[ 87, 161],
       [106, 174],
       [ 36,  76]])

In [39]:
arr3 = np.random.randint(0,10,size=(4,3))
arr4 = np.random.randint(0,10,size=(4,3))
arr3,arr4

(array([[6, 8, 7],
        [0, 7, 7],
        [2, 0, 7],
        [2, 2, 0]]),
 array([[4, 9, 6],
        [9, 8, 6],
        [8, 7, 1],
        [0, 6, 6]]))

In [40]:
np.dot(arr3.T,arr4)

array([[ 40,  80,  50],
       [ 95, 140, 102],
       [147, 168,  91]])

In [41]:
arr5 = np.random.randint(0,10,size=(4,3))
arr6 = np.random.randint(0,10,size=(4,3))
arr5,arr6

(array([[7, 4, 2],
        [7, 5, 2],
        [0, 2, 4],
        [2, 0, 4]]),
 array([[9, 6, 6],
        [8, 9, 9],
        [2, 6, 0],
        [3, 3, 4]]))

In [42]:
arr5>arr6

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [43]:
arr5>=arr6

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [44]:
arr5>7,arr6>7

(array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]),
 array([[ True, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False]]))

In [45]:
arr5==arr6

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [46]:
np.sort(arr5)

array([[2, 4, 7],
       [2, 5, 7],
       [0, 2, 4],
       [0, 2, 4]])

In [47]:
np.argsort(arr5)

array([[2, 1, 0],
       [2, 1, 0],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [48]:
np.argmax(arr6)

0

In [49]:
np.argmin(arr6)

8

In [50]:
np.argmax(arr6,axis=1)

array([0, 1, 1, 2], dtype=int64)

In [51]:
np.argmax(arr6,axis=0)

array([0, 1, 1], dtype=int64)

In [52]:
np.random.randn(3,5)

array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128, -0.21216142],
       [-0.42686879,  0.50144833,  1.15818665,  0.25711687,  0.3145129 ],
       [ 1.37186213,  0.17555329, -0.30928855,  0.6731255 , -0.25663018]])

In [53]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])